import type { Candidate } from './demoAkinatorTypes';

export const candidates: Candidate[] = [
  { name: 'Криштиану Роналду', facts: { real: true, alive: true, europe: true, sport: true, football: true, basketball: false, boxing: false, tennis: false, award: true, male: true, world: true } },
  { name: 'Лионель Месси', facts: { real: true, alive: true, latin: true, sport: true, football: true, basketball: false, boxing: false, tennis: false, award: true, male: true, world: true } },
  { name: 'Геннадий Головкин', facts: { real: true, alive: true, kz: true, sport: true, football: false, basketball: false, boxing: true, tennis: false, award: true, male: true, world: true } },
  { name: 'Леброн Джеймс', facts: { real: true, alive: true, usa: true, sport: true, football: false, basketball: true, boxing: false, tennis: false, award: true, male: true, world: true } },
  { name: 'Майкл Джордан', facts: { real: true, alive: true, usa: true, sport: true, football: false, basketball: true, boxing: false, tennis: false, award: true, male: true, world: true } },
  { name: 'Серена Уильямс', facts: { real: true, alive: true, usa: true, sport: true, football: false, basketball: false, boxing: false, tennis: true, female: true, world: true } },
  { name: 'Новак Джокович', facts: { real: true, alive: true, europe: true, sport: true, football: false, basketball: false, boxing: false, tennis: true, male: true, world: true } },
  { name: 'Рафаэль Надаль', facts: { real: true, alive: true, europe: true, sport: true, tennis: true, male: true, world: true } },
  { name: 'Роджер Федерер', facts: { real: true, alive: true, europe: true, sport: true, tennis: true, male: true, world: true } },
  { name: 'Килиан Мбаппе', facts: { real: true, alive: true, europe: true, sport: true, football: true, male: true, world: true } },
  { name: 'Эрлинг Холанд', facts: { real: true, alive: true, europe: true, sport: true, football: true, male: true, world: true } },
  { name: 'Неймар', facts: { real: true, alive: true, latin: true, sport: true, football: true, male: true, world: true } },
  { name: 'Льюис Хэмилтон', facts: { real: true, alive: true, europe: true, sport: true, racing: true, male: true, world: true } },
  { name: 'Макс Ферстаппен', facts: { real: true, alive: true, europe: true, sport: true, racing: true, male: true, world: true } },
  { name: 'Майк Тайсон', facts: { real: true, alive: true, usa: true, sport: true, boxing: true, male: true, world: true } },
  { name: 'Сауль Альварес', facts: { real: true, alive: true, latin: true, sport: true, boxing: true, male: true, world: true } },
  { name: 'Димаш Кудайберген', facts: { real: true, alive: true, kz: true, music: true, male: true, world: true } },
  { name: 'Иманбек', facts: { real: true, alive: true, kz: true, music: true, internet: true, male: true, world: true } },
  { name: 'Тейлор Свифт', facts: { real: true, alive: true, usa: true, music: true, award: true, female: true, world: true } },
  { name: 'Бейонсе', facts: { real: true, alive: true, usa: true, music: true, award: true, female: true, dance: true, world: true } },
  { name: 'Рианна', facts: { real: true, alive: true, usa: true, music: true, business: true, female: true, world: true } },
  { name: 'Леди Гага', facts: { real: true, alive: true, usa: true, music: true, actor: true, female: true, world: true } },
  { name: 'Billie Eilish', facts: { real: true, alive: true, usa: true, music: true, female: true, world: true } },
  { name: 'Ариана Гранде', facts: { real: true, alive: true, usa: true, music: true, actor: true, female: true, world: true } },
  { name: 'Джастин Бибер', facts: { real: true, alive: true, usa: true, music: true, male: true, world: true } },
  { name: 'Эд Ширан', facts: { real: true, alive: true, europe: true, music: true, male: true, world: true } },
  { name: 'Бруно Марс', facts: { real: true, alive: true, usa: true, music: true, male: true, world: true } },
  { name: 'Oliver Tree', facts: { real: true, alive: true, usa: true, music: true, internet: true, youtube: true, male: true, world: true } },
  { name: 'Эминем', facts: { real: true, alive: true, usa: true, music: true, rap: true, male: true, world: true } },
  { name: 'Дрейк', facts: { real: true, alive: true, usa: true, music: true, rap: true, male: true, world: true } },
  { name: 'Канье Уэст', facts: { real: true, alive: true, usa: true, music: true, rap: true, business: true, male: true, world: true } },
  { name: 'Кендрик Ламар', facts: { real: true, alive: true, usa: true, music: true, rap: true, male: true, world: true } },
  { name: 'Трэвис Скотт', facts: { real: true, alive: true, usa: true, music: true, rap: true, male: true, world: true } },
  { name: 'MrBeast', facts: { real: true, alive: true, usa: true, internet: true, youtube: true, male: true, world: true } },
  { name: 'Khaby Lame', facts: { real: true, alive: true, europe: true, internet: true, youtube: true, male: true, world: true } },
  { name: 'Илон Маск', facts: { real: true, alive: true, usa: true, business: true, internet: true, male: true, world: true } },
  { name: 'Джефф Безос', facts: { real: true, alive: true, usa: true, business: true, male: true, world: true } },
  { name: 'Марк Цукерберг', facts: { real: true, alive: true, usa: true, business: true, internet: true, male: true, world: true } },
  { name: 'Билл Гейтс', facts: { real: true, alive: true, usa: true, business: true, science: true, male: true, world: true } },
  { name: 'Уоррен Баффет', facts: { real: true, alive: true, usa: true, business: true, male: true, world: true } },
  { name: 'Сэм Альтман', facts: { real: true, alive: true, usa: true, business: true, science: true, male: true, world: true } },
  { name: 'Виталик Бутерин', facts: { real: true, alive: true, usa: false, business: true, crypto: true, science: true, male: true, world: true } },
  { name: 'Дуэйн Джонсон', facts: { real: true, alive: true, usa: true, actor: true, sport: true, football: false, basketball: false, boxing: false, tennis: false, male: true, world: true } },
  { name: 'Леонардо ДиКаприо', facts: { real: true, alive: true, usa: true, actor: true, award: true, male: true, world: true } },
  { name: 'Брэд Питт', facts: { real: true, alive: true, usa: true, actor: true, male: true, world: true } },
  { name: 'Том Круз', facts: { real: true, alive: true, usa: true, actor: true, male: true, world: true } },
  { name: 'Джонни Депп', facts: { real: true, alive: true, usa: true, actor: true, male: true, world: true } },
  { name: 'Роберт Дауни-младший', facts: { real: true, alive: true, usa: true, actor: true, award: true, male: true, world: true } },
  { name: 'Киану Ривз', facts: { real: true, alive: true, usa: true, actor: true, male: true, world: true } },
  { name: 'Уилл Смит', facts: { real: true, alive: true, usa: true, actor: true, music: true, male: true, world: true } },
  { name: 'Анджелина Джоли', facts: { real: true, alive: true, usa: true, actor: true, female: true, world: true } },
  { name: 'Скарлетт Йоханссон', facts: { real: true, alive: true, usa: true, actor: true, female: true, world: true } },
  { name: 'Марго Робби', facts: { real: true, alive: true, usa: true, actor: true, female: true, world: true } },
  { name: 'Эмма Уотсон', facts: { real: true, alive: true, europe: true, actor: true, female: true, world: true } },
  { name: 'Зендея', facts: { real: true, alive: true, usa: true, actor: true, music: true, female: true, world: true } },
  { name: 'Натали Портман', facts: { real: true, alive: true, usa: true, actor: true, female: true, world: true } },
  { name: 'Дженнифер Лоуренс', facts: { real: true, alive: true, usa: true, actor: true, female: true, world: true } },
  { name: 'Кристофер Нолан', facts: { real: true, alive: true, europe: true, actor: true, director: true, award: true, male: true, world: true } },
  { name: 'Квентин Тарантино', facts: { real: true, alive: true, usa: true, actor: true, director: true, male: true, world: true } },
  { name: 'Стивен Спилберг', facts: { real: true, alive: true, usa: true, actor: true, director: true, male: true, world: true } },
  { name: 'Джеймс Кэмерон', facts: { real: true, alive: true, usa: true, actor: true, director: true, male: true, world: true } },
  { name: 'Мартин Скорсезе', facts: { real: true, alive: true, usa: true, actor: true, director: true, male: true, world: true } },
  { name: 'Джеки Чан', facts: { real: true, alive: true, asia: true, actor: true, sport: true, male: true, world: true } },
  { name: 'BTS', facts: { real: true, alive: true, asia: true, music: true, kpop: true, male: true, dance: true, world: true } },
  { name: 'BLACKPINK', facts: { real: true, alive: true, asia: true, music: true, kpop: true, female: true, dance: true, world: true } },
  { name: 'Shah Rukh Khan', facts: { real: true, alive: true, asia: true, actor: true, male: true, world: true } },
  { name: 'Burak Ozcivit', facts: { real: true, alive: true, middleEast: true, actor: true, male: true, world: true } },
  { name: 'Ким Кардашьян', facts: { real: true, alive: true, usa: true, internet: true, business: true, model: true, female: true, world: true } },
  { name: 'Кайли Дженнер', facts: { real: true, alive: true, usa: true, internet: true, business: true, model: true, female: true, world: true } },
  { name: 'Кендалл Дженнер', facts: { real: true, alive: true, usa: true, model: true, female: true, world: true } },
  { name: 'Белла Хадид', facts: { real: true, alive: true, usa: true, model: true, female: true, world: true } },
  { name: 'Джиджи Хадид', facts: { real: true, alive: true, usa: true, model: true, female: true, world: true } },
  { name: 'Хейли Бибер', facts: { real: true, alive: true, usa: true, model: true, female: true, world: true } },
  { name: 'Жизель Бюндхен', facts: { real: true, alive: true, latin: true, model: true, female: true, world: true } },
  { name: 'iShowSpeed', facts: { real: true, alive: true, usa: true, internet: true, youtube: true, male: true, world: true } },
  { name: 'Касым-Жомарт Токаев', facts: { real: true, alive: true, kz: true, politics: true, male: true } },
  { name: 'Майкл Джексон', facts: { real: true, alive: false, usa: true, music: true, award: true, male: true, world: true } },
  { name: 'Коби Брайант', facts: { real: true, alive: false, usa: true, sport: true, football: false, basketball: true, boxing: false, tennis: false, award: true, male: true, world: true } },
  { name: 'Мухаммед Али', facts: { real: true, alive: false, usa: true, sport: true, football: false, basketball: false, boxing: true, tennis: false, male: true, world: true } },
  { name: 'Альберт Эйнштейн', facts: { real: true, alive: false, europe: true, science: true, male: true, world: true } },
  { name: 'Стив Джобс', facts: { real: true, alive: false, usa: true, business: true, male: true, world: true } },
  { name: 'Фредди Меркьюри', facts: { real: true, alive: false, europe: true, music: true, male: true, world: true } },
  { name: 'Пол Маккартни', facts: { real: true, alive: true, europe: true, music: true, male: true, world: true } },
  { name: 'Элтон Джон', facts: { real: true, alive: true, europe: true, music: true, male: true, world: true } },
  { name: 'Мадонна', facts: { real: true, alive: true, usa: true, music: true, female: true, world: true } },
  { name: 'Мик Джаггер', facts: { real: true, alive: true, europe: true, music: true, male: true, world: true } },
  { name: 'Тупак Шакур', facts: { real: true, alive: false, usa: true, music: true, male: true, world: true } },
  { name: 'Мэрилин Монро', facts: { real: true, alive: false, usa: true, actor: true, female: true, world: true } },
  { name: 'Абылай хан', facts: { real: true, alive: false, kz: true, politics: true, male: true } },
  { name: 'Абай Кунанбаев', facts: { real: true, alive: false, kz: true, writer: true, music: true, male: true } },
  { name: 'Александр Пушкин', facts: { real: true, alive: false, europe: true, writer: true, male: true, world: true } },
  { name: 'Уильям Шекспир', facts: { real: true, alive: false, europe: true, writer: true, male: true, world: true } },
  { name: 'Мұқағали Мақатаев', facts: { real: true, alive: false, kz: true, writer: true, male: true } },
  { name: 'Дж. К. Роулинг', facts: { real: true, alive: true, europe: true, writer: true, female: true, world: true } },
  { name: 'Человек-паук', facts: { real: false, screen: true, book: true, superheroUniverse: true, hero: true, magic: true, super: true, male: true, world: true } },
  { name: 'Гарри Поттер', facts: { real: false, screen: true, book: true, hero: true, magic: true, male: true, world: true } },
  { name: 'Джокер', facts: { real: false, screen: true, book: true, superheroUniverse: true, hero: false, male: true, world: true } },
  { name: 'Бэтмен', facts: { real: false, screen: true, book: true, superheroUniverse: true, hero: true, male: true, world: true } },
  { name: 'Шрек', facts: { real: false, screen: true, hero: true, magic: true, animal: true, male: true, world: true } },
  { name: 'Микки Маус', facts: { real: false, screen: true, hero: true, animal: true, world: true } },
  { name: 'Марио', facts: { real: false, game: true, hero: true, magic: true, male: true, world: true } },
  { name: 'Соник', facts: { real: false, game: true, screen: true, hero: true, animal: true, world: true } },
  { name: 'Наруто', facts: { real: false, anime: true, hero: true, magic: true, super: true, male: true, world: true } },
  { name: 'Гоку', facts: { real: false, anime: true, hero: true, magic: true, super: true, male: true, world: true } },
  { name: 'Луффи', facts: { real: false, anime: true, hero: true, magic: true, super: true, male: true, world: true } },
  { name: 'Лайт Ягами', facts: { real: false, anime: true, hero: false, magic: true, male: true, world: true } },
  { name: 'Леви Аккерман', facts: { real: false, anime: true, hero: true, male: true, world: true } },
  { name: 'Сейлор Мун', facts: { real: false, anime: true, hero: true, magic: true, super: true, female: true, world: true } },
  { name: 'Скриптонит', facts: { real: true, alive: true, kz: true, music: true, rap: true, male: true, world: true } },
  { name: 'Jah Khalib', facts: { real: true, alive: true, kz: true, almaty: true, music: true, rap: true, male: true, world: true } },
  { name: 'Moldanazar', facts: { real: true, alive: true, kz: true, music: true, male: true } },
  { name: 'Ninety One', facts: { real: true, alive: true, kz: true, music: true, qpop: true, male: true, teen: true } },
  { name: 'Dequine', facts: { real: true, alive: true, kz: true, music: true, female: true, teen: true } },
  { name: 'Ирина Кайратовна', facts: { real: true, alive: true, kz: true, music: true, internet: true, youtube: true, male: true, teen: true } },
  { name: 'Sadraddin', facts: { real: true, alive: true, kz: true, music: true, male: true, teen: true } },
  { name: 'Кайрат Нуртас', facts: { real: true, alive: true, kz: true, music: true, male: true } },
  { name: 'Роза Рымбаева', facts: { real: true, alive: true, kz: true, music: true, female: true, award: true } },
  { name: 'Шавкат Рахмонов', facts: { real: true, alive: true, kz: true, sport: true, male: true, world: true } },
  { name: 'Елена Рыбакина', facts: { real: true, alive: true, kz: true, sport: true, tennis: true, female: true, world: true } },
  { name: 'Ольга Рыпакова', facts: { real: true, alive: true, kz: true, sport: true, female: true, award: true } },
  { name: 'Илья Ильин', facts: { real: true, alive: true, kz: true, sport: true, male: true, award: true } },
  { name: 'Али Окапов', facts: { real: true, alive: true, kz: true, music: true, male: true } },
  { name: 'Алматинский тиктокер-подросток', facts: { real: true, alive: true, kz: true, almaty: true, teen: true, internet: true, tiktok: true } },
  { name: 'Алматинский школьник из частной школы', facts: { real: true, alive: true, kz: true, almaty: true, teen: true, world: false } },
  { name: 'Подросток из NIS Алматы', facts: { real: true, alive: true, kz: true, almaty: true, teen: true, science: true, world: false } },
  { name: 'Подросток из РФМШ Алматы', facts: { real: true, alive: true, kz: true, almaty: true, teen: true, science: true, world: false } },
  { name: 'Алматинский геймер-стример', facts: { real: true, alive: true, kz: true, almaty: true, teen: true, internet: true, streamer: true, youtube: true } },
  { name: 'Алматинская TikTok-блогерша', facts: { real: true, alive: true, kz: true, almaty: true, teen: true, internet: true, tiktok: true, female: true } },
  { name: 'Алматинский рэпер-подросток', facts: { real: true, alive: true, kz: true, almaty: true, teen: true, music: true, rap: true, male: true } },
  { name: 'Алматинский танцор из TikTok', facts: { real: true, alive: true, kz: true, almaty: true, teen: true, internet: true, tiktok: true, dance: true } },
];
